default:
  #Material that will replace the placed block.
  material: 'AIR'
  #Amount of seconds to wait before it replaces the block.
  time: 5

#Blocks that will decay once placed, it will use the default time.
whitelist:
  - WOOL

#Blocks with custom decay time
decay:
  WOOD:
    time: 5

#Enabled worlds where blocks will decay.
worlds:
  - 'world'
  - 'pvp_world'